### ISSUE TITLE
Vuetify Integration

### ISSUE THREAD

**Issue by dyardyGIT** [bencodezen/vue-enterprise-boilerplate#200]
Anyone tried to implement vuetify into the solution with any success?

thanks

**Comment by frandiox** [comment]
@dyardyGIT There's an issue about it [here](https://github.com/chrisvfritz/vue-enterprise-boilerplate/issues/48) with a common problem you might face.

**Comment by aburai** [comment]
Depends on vue-meta and can be resolved. My project runs with vue-enterprise-boilerplate and vuetify.

**Comment by marceloavf** [comment]
Have you successfully imported Vuetify  @dyardyGIT ? If needed, I can create a branch with these changes to help you.

**Comment by fgauris** [comment]
@marceloavf I'm certain that having branch with Vuetify integrated would help a lot of people who want to use this boilerplate and Vuetify.

**Comment by silkster** [comment]
A better solution would be for someone to fork this repo and add Vuetify to keep this repo as clean as possible.

**Comment by ngocnv371** [comment]
I have integrated vuetify in a fork, check this out here https://github.com/ngocnv371/vue-enterprise-boilerplate-vuetify
