### ISSUE TITLE
yarn build failed in github action

### ISSUE THREAD

**Issue by tuhin47** [bencodezen/vue-enterprise-boilerplate#209]
I wrote an action for GitHub. It doesn't work using [yarn](https://github.com/tuhin47/vue-enterprise-boilerplate/actions/runs/164910983/workflow). But works properly by [npm](https://github.com/tuhin47/vue-enterprise-boilerplate/actions/runs/164920689). 
My npm action `main.xml` code 

> name: ubuntu
> on:
>   push:
>     branches: [master]
>   pull_request:
>     branches: [master]
> jobs:
>   normal-run:
>     runs-on: ubuntu-latest
>     steps:
>       - name: Checkout
>         uses: actions/checkout@v1
>       - name: Install Xvfb libxss1
>         run: sudo apt-get install xvfb libxss1
>       - name: npm install
>         run: npm install --no-optional
>       - name: build
>         run: npm run build
- [ Please provide a recommended  GitHub workflow action]

**Comment by borysl** [comment]
I actually downloaded boilerplate today and find out that with yarn it doesn't work spewing suspect exception in one of the dependencies), while it did work with npm. More over npm takes less time.
```
> npm -v
6.14.8
>node -v
v14.15.1
>yarn -v
1.22.10
```

so currently I found npm more useful.
