### ISSUE TITLE
Relative imports from parent directories are not allowed.

### ISSUE THREAD

**Issue by jomellelastrilla** [bencodezen/vue-enterprise-boilerplate#214]
Can  you help me with this compiling error

https://prnt.sc/tvmo3w

**Comment by moosemanf** [comment]
I'm also wondering why vue and vuex is not recognized as a package?!

**Comment by moosemanf** [comment]
but you can change the error to a warning `warn` or disable the according rule:

`'import/no-relative-parent-imports': 'warn'`  in .eslintrc.js
