### ISSUE TITLE
Error in test unit. something wrong with config, maybe

### ISSUE THREAD

**Issue by impeiran** [bencodezen/vue-enterprise-boilerplate#219]
the following's can reappear in: https://github.com/impeiran/vue-enterprise-boilerplate

1. jest doesnt support webpack's API: require.context, and then it occurs the error
![image](https://user-images.githubusercontent.com/32994681/92710843-b66f3800-f38a-11ea-8344-0cdb3786f173.png) 
i found a solution to resolve it. from: https://stackoverflow.com/questions/38332094/how-can-i-mock-webpacks-require-context-in-jest/54151648#54151648

2. after solving the first problem, it comes the second:
imported module but undefined,  i have no idea to fix it, and im pretty sure the path and the babel config are fine.
![image](https://user-images.githubusercontent.com/32994681/92711967-9ab86180-f38b-11ea-8594-df60b9abe20a.png)

**Comment by beamsies** [comment]
I'm having the same issue. 

I don't know how to mock this as I'm new to unit testing in Jest.

**Comment by boydaihungst** [comment]
For anyone whom have this problem. Put this in jest.config.js
```javascript
  globals: {
    __requireContext: () => {
      function requireContext() {}
      requireContext.keys = () => [];

      return requireContext;
    },
  },
```

**Comment by boydaihungst** [comment]
Solution here: [https://github.com/storybookjs/storybook/issues/2487#issuecomment-505453704](url)
