### ISSUE TITLE
Dependency Injection into Vuex Modules

### ISSUE THREAD

**Issue by CVANCGCG** [bencodezen/vue-enterprise-boilerplate#223]
I'm looking for some guidance on how to correctly inject a GraphQL (Vue Apollo Typescript)  or Axios client into the Vuex store. Having spent time, researching, I still have not found a solution that works that feels aligned with the Vue Enterprise Boiler Plate.

**My environment**
I have strongly typed state for each of my modules. When dispatching an action from Vue Components, I also pass in the Vue Apollo client to each and every invocation. As our application grows, I need to integrate other APIs; such as new  RESTful endpoints or different GQL servers. In the worst case, I would need to modify each and every Action and dispatch to pass in an additional Axios client or other services. This approach feels brittle, inelegant, and not extensible as the number of services required within my Vuex Action grows. Is there an established solution that works well with the BoilerPlate that is consistent with its State Management convention defined solution?

**What have I've attempted to explore?**
1. Inversify DI via @Inject here: https://medium.com/@fernalvarez/dependency-injection-made-easy-for-vuejs-and-vuex-with-typescript-3bc738c17e05
This feels like a heavy coercion into a Class based solution. I'm reluctant to use a Class based solution for this alone; especially not knowing how much of the Vue Enterprise Boilerplate initializers and helper methods will also break in its dynamic/meta/hot reloading code to build the namespaced stores.

2. Factory Functions documented here: https://codeburst.io/dependency-injection-with-vue-js-f6b44a0dae6d
This feels like a better fit than #1 but I am having a hard time distilling what needs to be adapted within the Vue Enterprise Vuex Store and Module builder functions to receive instantiated GraphQL and Axios instInces as a parameter that it in turn builds a closure arround. I am thinking that some currying function would help but I am having troubles figuring out how to adapt this block of code. 
```
// Register each file as a corresponding Vuex module. Module nesting
// will mirror [sub-]directory hierarchy and modules are namespaced
// as the camelCase equivalent of their file name.

import camelCase from 'lodash/camelCase'

const modulesCache = {}
const storeData = {
  modules: {}
};

(function updateModules() {
  // Allow us to dynamically require all Vuex module files.
  // https://webpack.js.org/guides/dependency-management/#require-context
  const requireModule = require.context(
    // Search for files in the current directory.
    '.',
    // Search for files in subdirectories.
    true,
    // Include any .js|.ts files that are not this file or a unit test.
    /^((?!index|\.unit\.).)*\.(js|ts)$/
  )

  // For every Vuex module...
  requireModule.keys().forEach(fileName => {
    const moduleDefinition = requireModule(fileName)

    // Skip the module during hot reload if it refers to the
    // same module definition as the one we have cached.
    if (modulesCache[fileName] === moduleDefinition) return

    // Update the module cache, for efficient hot reloading.
    modulesCache[fileName] = moduleDefinition

    // Get the module path as an array.
    const modulePath = fileName
      // Remove the "./" from the beginning.
      .replace(/^\.\//, '')
      // Remove the file extension from the end.
      .replace(/\.\w+$/, '')
      // Split nested modules into an array path.
      .split(/\//)
      // camelCase all module namespaces and names.
      .map(camelCase) as []

    // Get the modules object for the current path.
    const { modules } = getNamespace(storeData, modulePath)

    // Add the module to our modules object.
    modules[modulePath.pop()] = {
      // Modules are namespaced by default.
      namespaced: true,
      ...moduleDefinition
    }
  })

  // If the environment supports hot reloading...
  if (module.hot) {
    // Whenever any Vuex module is updated...
    module.hot.accept(requireModule.id, () => {
      // Update `storeData.modules` with the latest definitions.
      updateModules()
      // Trigger a hot update in the store.
      require('../store').default.hotUpdate({
        modules: storeData.modules
      })
    })
  }
})()

// Recursively get the namespace of a Vuex module, even if nested.
function getNamespace(subtree, path) {
  if (path.length === 1) return subtree

  const namespace = path.shift()
  subtree.modules[namespace] = {
    modules: {},
    namespaced: true,
    ...subtree.modules[namespace]
  }
  return getNamespace(subtree.modules[namespace], path)
}

export default storeData.modules

```

**Comment by silkster** [comment]
If you’re using Apollo, you might think about replacing Vuex with Apollo cache. Apollo does a lot more than just query Graphql. I highly recommend learning all the capabilities of Apollo client first before trying to wedge it into this project. What you should end up with is a fork of this project using Apollo without Vuex.

**Comment by silkster** [comment]
Axios is already included here.

**Comment by CVANCGCG** [comment]
Hi @silkster, I appreciate the recommendation and will look into Apollo Cache as well. I've generally overriden it per invocation because our app requires real time transactional data. 

Will you clarify what you meant by ``"Axios is already included here?"``
