### ISSUE TITLE
Is this a typo or intentional?

### ISSUE THREAD

**Issue by FrozenHearth** [bencodezen/vue-enterprise-boilerplate#225]
In utils sub-section in Architecture section, the following is written;

> These are utility functions you may want to share between many files
> in your application. They will always be pure and never have side
> effects, meaning if you provide a function the same arguments, it will
> always return the same result. These should also never directly affect
> the DOM or interface with our Vuex state.

Shouldn't it be "interfere", instead of "interface"?

Link: https://github.com/chrisvfritz/vue-enterprise-boilerplate/blob/master/docs/architecture.md#utils

**Comment by olore** [comment]
My opinion:

"interface" here makes sense to me. As in it will "never communicate with" the Vuex state.

"interfere" is not a bad option, but to me, it implies that it will "not cause a problem for" the Vuex state. Which is true, but not as precise as saying it will not communicate with it
