### ISSUE TITLE
TypeError: ext[key].bind is not a function

### ISSUE THREAD

**Issue by saroha-sandeep** [bencodezen/vue-enterprise-boilerplate#229]
yarn run v1.22.10
$ vue-cli-service serve --open
 INFO  Starting development server...
 ERROR  TypeError: ext[key].bind is not a function
TypeError: ext[key].bind is not a function
    at C:\Users\Admin\project\greatid\node_modules\css-select\node_modules\domutils\index.js:12:28
    at Array.forEach (<anonymous>)
    at C:\Users\Admin\project\greatid\node_modules\css-select\node_modules\domutils\index.js:11:19
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (C:\Users\Admin\project\greatid\node_modules\css-select\node_modules\domutils\index.js:10:3)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by suryarajendhran** [comment]
Could you share steps to reproduce the issue?

**Comment by cappe** [comment]
@saroha-sandeep I'm facing exactly the same problem. Tried to upgrade some npm packages, and something failed. Reverted everything back but the problem stayed. Now I cannot boot the thing.

`yarn install` finishes ok but `yarn serve` (or `vue-cli-service serve` fails) as it seems to be with you too. I get exactly the same error.

I tried to reproduce the issue by creating a fresh project with `vue-cli` but everything seemed to work. I also copied the problematic `package.json` to the fresh project but could not reproduce the issue.

I understand this comment may not provide too much value but thought to let you know.

My environment is as follows:

- macOS 12.2.1
- docker 20.10.11
- docker-compose 1.29.2
- Docker image based on `node:10-alpine` and later `node:16.15.1-alpine`, failed on both
- @vue/cli 5.0.6

And here's the problematic `package.json`:

```
{
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint",
    "start": "node server.js"
  },
  "dependencies": {
    "@rails/activestorage": "^6.0.1",
    "@sentry/tracing": "^7.2.0",
    "@sentry/vue": "^7.2.0",
    "chart.js": "^2.9.3",
    "core-js": "^3.3.2",
    "dayjs": "^1.8.17",
    "express": "^4.17.1",
    "fabric": "^3.5.1",
    "js-cookie": "^2.2.1",
    "register-service-worker": "^1.6.2",
    "serve-static": "^1.14.1",
    "video.js": "^7.8.4",
    "vue": "^2.6.10",
    "vue-gtm": "^2.2.0",
    "vue-router": "^3.1.3",
    "vue-wait": "^1.4.8",
    "vuetify": "2.1.11",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^4.0.0",
    "@vue/cli-plugin-eslint": "^4.0.0",
    "@vue/cli-plugin-pwa": "^4.0.0",
    "@vue/cli-plugin-router": "^4.0.0",
    "@vue/cli-plugin-vuex": "^4.0.0",
    "@vue/cli-service": "^4.0.0",
    "@vue/eslint-config-airbnb": "^4.0.0",
    "babel-eslint": "^10.0.3",
    "eslint": "^5.16.0",
    "eslint-plugin-vue": "^5.0.0",
    "sass": "~1.32.12",
    "sass-loader": "^8.0.2",
    "vue-cli-plugin-vuetify": "^2.0.2",
    "vue-template-compiler": "^2.6.10",
    "vuetify-loader": "^1.3.0"
  }
}
```

**Comment by cappe** [comment]
I was able to make it work by deleting the image and all intermediate build images, and then re-build it with `docker compose build --no-cache <YOUR_SERVICE>`. The issue persisted because of some caching issue.

I'll try to reproduce the issue by upgrading the packages again.
