### ISSUE TITLE
Change app.config.json at runtime

### ISSUE THREAD

**Issue by mohammad-zr** [bencodezen/vue-enterprise-boilerplate#232]
Is it possible to change app.config.json values after publish without need to rebuilding app?

**Comment by bencodezen** [comment]
It depends on your compilation strategy. If the app.config.json is bundled with the build, then I don't think it can be separated; but if you deploy the JSON file as a separate request, then it should theoretically be possible.

Sorry for not being able to provide a more concrete answer, but I hope this helps!
