### ISSUE TITLE
Updated dependencies release?

### ISSUE THREAD

**Issue by PinkFromTheFuture** [bencodezen/vue-enterprise-boilerplate#238]
This project is recommended in many places, but it's been a while since it received updates for new versions of dependencies. Vuex for example has been replaced by Pinia.

I've been trying to find a fork that has updated dependencies, but I just can't find any.

Anybody has any clues?

**Comment by bencodezen** [comment]
Hi @PinkFromTheFuture! Sorry for the lapse in the project updates. You should see new changes coming to the project going forward to reflect the current ecosystem. If you have any questions, please don't hesitate to file another issue!
